version: "2"
services:
  app:
    build: ./chatroom
    container_name: "Final-WebApp"
    depends_on:
      - redis
    ports:
      - '5000:5000'
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
