version: "2"
services:
  app:
    build: ./app
    container_name: "Final-WebApp"
    depends_on:
      - redis
    ports:
      - '443:443'




  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
