version: "2"
services:
  app:
    build: ./app
    container_name: "Final-WebApp"
    depends_on:
      - redis
      - postgres
    ports:
      - '443:443'
    entrypoint:
      - flask
      - run
      - --host='0.0.0.0'

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
