version: "2"
services:
  app:
    build: ./app
    container_name: "Final-WebApp"
    depends_on:
      - redis
    links:
      - postgres
    ports:
      - '443:443'
    networks:
      - default
    entrypoint:
      - flask
      - run
      - --host='0.0.0.0'

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - default
