version: "2"
services:
  app:
    build: ./app
    container_name: "Final-WebApp"
    ports:
      - '443:443'

  chatroom:
    build: ./chatroom
    container_name: "Final-Chatroom"
    ports:
      - '5000:5000'
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
